Restructure code
thenativeweb/eslint-config-es pull request #433
Opened 2021-11-04 14:58 UTC by davelosert

In this pr, we want to tackel several tasks:

- [ ] Switch to typescript
- [ ] Split all rules across several files instead of having it all in `node.js`
- [ ] Let `browser.js` and `node.js` extend a default-configuration rather than having `browser.js` extend `node.js`
- [ ] Use a new format (BetterRules) for rules that allow a more precise syntax 
- [ ] Allow functions as configuration arguments to be more dynamic with conditional configs (e.g. typescript vs. javascript)
- [ ] Writes some initial hooks (`usePlugin`, `useConditionalTs`) to use
- [ ] Write a hook to use `unicorn`-overwrites in core rules

2021-11-04 15:25 UTC, davelosert commented
@goloroden , @yeldiRium : this is ready for review.
The build failure is due to a failing dependency check with the package `cyclist` which is a sub-sub-sub-dependency of `semantic-release-configuration`. This should have actually failed already there - so I don't quite get why is only failing here.

However, as this will probably be fixed elsewhere, you could already start reviewing my changes here.

2021-11-05 08:53 UTC, yeldiRium commented
> This should have actually failed already there - so I don't quite get why is only failing here.

As far as I can see in the failing action the problem is a licence incompatibility with us, which is due to cyclist v0.2.2 not having declared any license. We can safely add it as having an MIT license though, since they added the MIT license in a later commit. I'll add it to the license configuration

2021-11-05 09:24 UTC, yeldiRium requested changes
Amazing work! I am really impressed with how tidy this has turned out. I believe this will make the maintenance of the rule-set much easier in the future.

I have some questions, nitpicks and improvements, though :D

2021-11-05 09:24 UTC, yeldiRium commented on lib/isInstalled.ts
>        // non-needed variable.
I assume we can remove this and the caught exception below xD I would be very surprised if this is still relevant.

2021-11-05 09:24 UTC, yeldiRium commented on lib/pickRuleFor.ts
> +import { Language } from './Language';
Let's rename this file to `pickRulesFor.ts`, so that the file name is identical to the exported function.

2021-11-05 09:24 UTC, yeldiRium commented on lib/Language.ts
> +type Language = 'typeScript' | 'javaScript';
I believe we usually treat `typescript` and `javascript` as one word each, so i would not capitalize the `s` in the middle for consistency.

2021-11-05 09:24 UTC, yeldiRium commented on lib/betterRules/compile.ts
> +  if (ruleName.includes('/')) {
What do you think about moving the `fixReactEs6Rule` functionality here? It would make the `defaultConfiguration` a bit cleaner and hide the weirdness of formatting the rule names. Or could that conflict with the names of other rules?

2021-11-05 09:24 UTC, yeldiRium commented on lib/defaultConfiguration.ts
> +const fixReactEs6Rule = (reactRulesRecord: Linter.RulesRecord): Linter.RulesRecord =>
Same as above, maybe consider moving this to `compile`?

2021-11-05 09:24 UTC, yeldiRium commented on package.json
> +  "main": "build/lib/defaultConfig.js",
Not really sure what I prefer here, but this could stay as `node.js`, couldn't it? `node.js` exports the same things `defaultConfig.js` does and it is the more obvious entrypoint to the library.

Also I don't think we need to export types from this package, since it is not really intended for programmatic consumption. And even if it were, we'd have to export `build/lib/index.d.ts`, not the types from `defaultConfig`.

2021-11-05 09:24 UTC, yeldiRium commented on test/unit/betterRules/compileTests.ts
> +  test('compiles a rule with a  boolean to a deactivated rule.', async (): Promise<void> => {
There a redundant space in here.

```suggestion
  test('compiles a rule with a boolean to a deactivated rule.', async (): Promise<void> => {
```

2021-11-05 09:24 UTC, yeldiRium commented on test/unit/betterRules/compileTests.ts
> +  test('leaves plugin-names in tact when converting.', async (): Promise<void> => {
```suggestion
  test('leaves plugin-names intact when converting.', async (): Promise<void> => {
```

2021-11-05 09:31 UTC, davelosert commented on package.json
> +  "main": "build/lib/defaultConfig.js",
You are right.
But I think I would prefer exporting `build/lib/index.ts` as entry point.
This allows for programatically extending the rules and also using the `betterRules` package elsewhere. WDYT?

(Even though it's not intended yet, having the possibility seems nice)

2021-11-05 09:40 UTC, davelosert commented on lib/betterRules/compile.ts
> +  if (ruleName.includes('/')) {
It was there initially.

However - I kind of want to treat the `betterRules` Folder as if it was a generic plugin.
And this is a special 'bug' for a special package (`react`) that we are using.

So I found the right place was actually 'outside'.

I was thinking about providing an option to compile to be able to `postProcess` rules and then put it there. But since, at least right now, it is only this one single rule, that would be a bit premature imho.

Long story short:
For now, I'd preffer to leave it outside of the `betterRules` package. Understandable?

2021-11-05 09:41 UTC, davelosert commented on lib/defaultConfiguration.ts
> +const fixReactEs6Rule = (reactRulesRecord: Linter.RulesRecord): Linter.RulesRecord =>
See my comment above.

2021-11-05 09:43 UTC, davelosert commented on lib/Language.ts
> +type Language = 'typeScript' | 'javaScript';
As written in Slack, this is the technically correct form (as it is `JavaScript` and `TypeScript`), so we leave it here 🙂

2021-11-05 09:46 UTC, davelosert commented on lib/pickRuleFor.ts
> +import { Language } from './Language';
Done - good catch. 🙂

2021-11-05 09:46 UTC, davelosert commented on lib/isInstalled.ts
>        // non-needed variable.
It's gone. 👍🏻

2021-11-05 10:09 UTC, yeldiRium commented on lib/betterRules/compile.ts
> +  if (ruleName.includes('/')) {
Understandable :+1:

2021-11-05 10:10 UTC, yeldiRium commented on package.json
> +  "main": "build/lib/defaultConfig.js",
I like that solution too. So people using this as an eslint config package extend `es/node` as they did before, but if they want to use our functionality, they can import the package as `import {} from 'eslint-config-es`. Good solution :+1:

2021-11-05 10:21 UTC, yeldiRium approved these changes

2021-11-05 10:24 UTC, yeldiRium approved these changes

2021-11-05 12:05 UTC, yeldiRium submitted a review, later dismissed

2021-11-06 13:47 UTC, goloroden requested changes
Hey @davelosert 👋 

I also took a look at your PR, and I can only confirm what @yeldiRium had already said: Especially the definitions of the rules become so much more readable 🎉

Great work!
(Oh, and also a great idea to export the `betterRule` part.)

What I have not yet reviewed is the `README.md` file, and the workflows for GitHub Actions. However, both shoudn't be a blocker for meging.

2021-11-06 13:47 UTC, goloroden commented on lib/Language.ts
> +type Language = 'typeScript' | 'javaScript';
I double-checked this, and @yeldiRium is right – everywhere else where we had to make a difference between these two languages, we used the all-lowercase version, as if it was a single word. It is correct that the official spelling is with the uppercase `S`, but for the sake of consistency we should turn it into all-lowercase as well.

@davelosert Can you please adjust this once again? Sorry for the unnecessary work, this was clearly my fault.

2021-11-06 13:47 UTC, goloroden commented on lib/betterRules/BetterRulesRecord.ts
> +// This is named "BetterRulesRecord" because we replace the ESLint Type Linter.RulesRecord
```suggestion
// This is named "BetterRulesRecord" because we replace the ESLint built-in type "Linter.RulesRecord".
```

2021-11-06 13:47 UTC, goloroden commented on lib/defaultConfiguration.ts
> +  ecmaVersion: 12,
Is there an option to have this as "stable" or "latest" or something like that, so that we don't have to adjust this from year to year?

2021-11-06 13:47 UTC, goloroden commented on lib/defaultConfiguration.ts
> +  // @ts-expect-error react is actuall set by the plugin
```suggestion
  // @ts-expect-error react is actually set by the plugin.
```

2021-11-06 13:47 UTC, goloroden commented on lib/rules/react.ts
> +
Why this empty line, and why having two distinct blocks for JSX- and non-JSX-rules?

2021-11-06 13:47 UTC, goloroden commented on lib/rules/sharedCoreTypeScript.ts
> +  // but for typescript we want it deactivated and replaced by namingConvention
```suggestion
  // camelCase is a corner case - as for TypeScript, we only want it for JavaScript,
  // but for TypeScript we want it deactivated and replaced by namingConvention
```

2021-11-06 13:47 UTC, goloroden commented on lib/rules/sharedCoreTypeScript.ts
> +import { BetterRulesRecord } from '../betterRules';
This file should then be named `sharedCoreTypescript.ts`.

2021-11-06 13:47 UTC, goloroden commented on lib/rules/unicorn.ts
> +  // The noNewBuffer rule does the same thing as ESLint's builtIn
```suggestion
  // The noNewBuffer rule does the same thing as ESLint's built-in
```

2021-11-06 13:47 UTC, goloroden commented on lib/rules/unicorn.ts
> +
Why this empty line?

2021-11-06 13:47 UTC, goloroden commented on node.js
> +const defaultEslintConfiguration = require('./build/lib/defaultConfiguration');
Shouldn't the variable just be named `defaultConfiguration`, as in the `browser.js` file as well?

2021-11-06 13:47 UTC, goloroden commented on test/integration/dummyTs/dummy.ts
> +// It is not actually used as we are using strings for our tests - but it avoids the error
```suggestion
// It is not actually used as we are using strings for our tests - but it avoids the error.
```

2021-11-06 13:47 UTC, goloroden commented on test/integration/dummyTs/dummyTsx.tsx
> +// It is not actually used as we are using strings for our tests - but it avoids the error
```suggestion
// It is not actually used as we are using strings for our tests - but it avoids the error.
```

2021-11-06 13:47 UTC, goloroden commented on test/integration/esLintTester.ts
> +import * as defaultConfig from '../../lib/defaultConfiguration';
```suggestion
import * as defaultConfiguration from '../../lib/defaultConfiguration';
```

2021-11-07 16:41 UTC, davelosert commented on lib/rules/sharedCoreTypeScript.ts
> +  // but for typescript we want it deactivated and replaced by namingConvention
Changing the first word to `camelCase` won't work as comments have to start with an upper case letter (that's the rules ;)). So I accpeted this suggestion but will have to change that again with my next commit.

2021-11-07 16:42 UTC, davelosert commented on lib/Language.ts
> +type Language = 'typeScript' | 'javaScript';
No problem. I switched it back to lowercase.

2021-11-07 16:43 UTC, davelosert commented on lib/defaultConfiguration.ts
> +  ecmaVersion: 12,
There is `latest` which I used now.
However, due to an error in the types-package, typescript complains about it.

I fixed it with a `@ts-expect-error` comment now. Might send a PR to the `types` Repo later this week so we can remove the comment.

2021-11-07 16:45 UTC, davelosert commented on lib/rules/react.ts
> +
No reason.

I guess the jsx-separation was the sort-order before and I did not realize it.

I now put all jsx-rules into the upper block where they belong alphabetically.

2021-11-07 16:45 UTC, davelosert commented on lib/rules/unicorn.ts
> +
No reason, i removed it.

2021-11-07 16:46 UTC, davelosert commented on node.js
> +const defaultEslintConfiguration = require('./build/lib/defaultConfiguration');
yep, good catch. Renamed it.

2021-11-07 16:53 UTC, davelosert commented
@goloroden : Thanks a lot for the feedback. i put in all your requested changes.

One thing though: You did not leave any feedback for the integration tests.
Did you have a look at those as well?

One Change I did here (after feedback I got from @yeldiRium in Slack): Put all the Test-utilities into the `test/shared` Folder.

2021-11-07 23:16 UTC, goloroden commented on lib/rules/sharedCoreTypeScript.ts
> +  // but for typescript we want it deactivated and replaced by namingConvention
What about „The rule camelCase …“?

2021-11-07 23:17 UTC, goloroden commented
Meanwhile, I have, and I‘m fine with them. 

So from my POV there is only the workflows and the documentation left.

2021-11-08 08:59 UTC, davelosert commented
@goloroden , @yeldiRium - one little update:

 I just added a `todo` comment for the `ecmaVersion` fix that expires on the next `@types/eslint` Version (see [here](https://github.com/thenativeweb/eslint-config-es/pull/433/files#diff-4ffe59dd7ff4e3231ca8cb82496318ec6f9dfbe4d57bfde2c94c4d542d1a22daR20)) as I created a [PR to fix this issue in the `DefinitlyTypes`-Repository](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57037)

2021-11-10 10:11 UTC, yeldiRium submitted a review, later dismissed

2021-11-12 13:18 UTC, goloroden requested changes
Hey @davelosert 👋
Hey @yeldiRium 👋

I've reviewed it once again, and I have a few things left … could you please have a look at the comments?

2021-11-12 13:18 UTC, goloroden commented on lib/rules/sharedCoreTypescript.ts
> +import { BetterRulesRecord } from '../betterRules';
This file is named wrong IMHO – it should be `createSharedRulesFor.ts`, since that's what it exports.

2021-11-12 13:18 UTC, goloroden commented on test/integration/rules/sharedCoreTypeScriptTests.ts
> +import { lintJavaScript, lintTsx, lintTypeScript } from '../../shared/esLintTester';
The functions `lintJavaScript` and `lintTypeScript` need to be renamed to use a lowercase `s`, to conform to the spelling everywhere else.

2021-11-12 13:18 UTC, goloroden commented on test/shared/esLintTester.ts
> +const lintJavaScript = async (codeString: string): Promise<ESLint.LintResult[]> =>
```suggestion
const lintJavascript = async (codeString: string): Promise<ESLint.LintResult[]> =>
```

2021-11-12 13:18 UTC, goloroden commented on test/shared/esLintTester.ts
> +const lintTypeScript = async (codeString: string): Promise<ESLint.LintResult[]> =>
```suggestion
const lintTypescript = async (codeString: string): Promise<ESLint.LintResult[]> =>
```

2021-11-12 13:18 UTC, goloroden commented on test/unit/betterRules/compileTests.ts
> +import { assert } from 'assertthat';
Shouldn't this file be named `rulesCompilerTests.ts`?

2021-11-12 13:18 UTC, goloroden commented on tsconfig.json
> +    "test/shared/dummyTs/dummyTsx.tsx"
To be consistent with the other paths:

```suggestion
    "./test/shared/dummyTs/dummyTsx.tsx"
```

2021-11-17 07:13 UTC, davelosert commented on lib/rules/sharedCoreTypescript.ts
> +import { BetterRulesRecord } from '../betterRules';
Note sure if that helps the reader in this case. Especially as there might be other shared rules with other plugins in the future.

Or would you put them then all into this file?

2021-11-17 07:15 UTC, davelosert commented on test/unit/betterRules/compileTests.ts
> +import { assert } from 'assertthat';
The file it tests is named `compile.ts` - shouldn't it be named the same?

2021-11-17 07:19 UTC, davelosert commented
👋🏻 Hi @goloroden ,

I had a looked. I fixed some things but have a few questions left on three comments. 🙂

2021-11-17 08:27 UTC, yeldiRium commented on test/unit/betterRules/compileTests.ts
> +import { assert } from 'assertthat';
The top level suit should be `suite('compile')...` ;) This should clear up the confusion.

2021-11-17 08:37 UTC, goloroden commented on test/unit/betterRules/compileTests.ts
> +import { assert } from 'assertthat';
That's true 👍

2021-11-17 08:39 UTC, goloroden commented on lib/rules/sharedCoreTypescript.ts
> +import { BetterRulesRecord } from '../betterRules';
Ah okay, now I understand – okay, then this is fine for me 👍

2021-11-17 13:26 UTC, davelosert commented on test/unit/betterRules/compileTests.ts
> +import { assert } from 'assertthat';
Ah yeah, sorry for the confusion. I already fixed it so should be correct now. 👍🏻

2021-11-17 19:37 UTC, davelosert commented
Again hi @goloroden & @yeldiRium : I guess everything is fine now and we are ready for merge?

2021-11-17 19:44 UTC, goloroden approved these changes
From my side we are good to go 😊

(I still haven’t reviewed the workflows and the documentation, but this can still be done after merging IMHO)

2021-11-17 19:45 UTC, goloroden commented
PS: @yeldiRium If you are fine with this, too, please feel free to merge 😊

2021-11-19 08:11 UTC, merged